'preserve_hierarchy': false
'export_languages': ['de', 'en', 'fr', 'es-ES', 'ta', 'hi']

'files':
  [
    {
      'source': '/apps/frontend/src/data/en/index.ts',
      'translation': '/apps/frontend/src/data/%two_letters_code%/index.ts',
    },
  ]
