name: e2e tests
on:
  workflow_dispatch:
  push:
    branches:
      - staging
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e-tests
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: actions/checkout@v3
      - uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 1200
          check_interval: 20
      - run: yarn
      - run: yarn playwright install --with-deps chromium
      - run: yarn e2e-workers
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-screenshots-on-fail
          path: output/ # or path/to/artifact
